// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocoloAtt.proto

package protocoloAtt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NuevoAvionRequest struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Linea                string   `protobuf:"bytes,2,opt,name=linea,proto3" json:"linea,omitempty"`
	Destino              string   `protobuf:"bytes,3,opt,name=destino,proto3" json:"destino,omitempty"`
	Peso                 int32    `protobuf:"varint,4,opt,name=peso,proto3" json:"peso,omitempty"`
	Combustible          int32    `protobuf:"varint,5,opt,name=combustible,proto3" json:"combustible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NuevoAvionRequest) Reset()         { *m = NuevoAvionRequest{} }
func (m *NuevoAvionRequest) String() string { return proto.CompactTextString(m) }
func (*NuevoAvionRequest) ProtoMessage()    {}
func (*NuevoAvionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{0}
}

func (m *NuevoAvionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NuevoAvionRequest.Unmarshal(m, b)
}
func (m *NuevoAvionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NuevoAvionRequest.Marshal(b, m, deterministic)
}
func (m *NuevoAvionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NuevoAvionRequest.Merge(m, src)
}
func (m *NuevoAvionRequest) XXX_Size() int {
	return xxx_messageInfo_NuevoAvionRequest.Size(m)
}
func (m *NuevoAvionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NuevoAvionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NuevoAvionRequest proto.InternalMessageInfo

func (m *NuevoAvionRequest) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *NuevoAvionRequest) GetLinea() string {
	if m != nil {
		return m.Linea
	}
	return ""
}

func (m *NuevoAvionRequest) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

func (m *NuevoAvionRequest) GetPeso() int32 {
	if m != nil {
		return m.Peso
	}
	return 0
}

func (m *NuevoAvionRequest) GetCombustible() int32 {
	if m != nil {
		return m.Combustible
	}
	return 0
}

type NuevoAvionResponse struct {
	Direccion            string   `protobuf:"bytes,1,opt,name=direccion,proto3" json:"direccion,omitempty"`
	Origen               string   `protobuf:"bytes,2,opt,name=origen,proto3" json:"origen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NuevoAvionResponse) Reset()         { *m = NuevoAvionResponse{} }
func (m *NuevoAvionResponse) String() string { return proto.CompactTextString(m) }
func (*NuevoAvionResponse) ProtoMessage()    {}
func (*NuevoAvionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{1}
}

func (m *NuevoAvionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NuevoAvionResponse.Unmarshal(m, b)
}
func (m *NuevoAvionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NuevoAvionResponse.Marshal(b, m, deterministic)
}
func (m *NuevoAvionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NuevoAvionResponse.Merge(m, src)
}
func (m *NuevoAvionResponse) XXX_Size() int {
	return xxx_messageInfo_NuevoAvionResponse.Size(m)
}
func (m *NuevoAvionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NuevoAvionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NuevoAvionResponse proto.InternalMessageInfo

func (m *NuevoAvionResponse) GetDireccion() string {
	if m != nil {
		return m.Direccion
	}
	return ""
}

func (m *NuevoAvionResponse) GetOrigen() string {
	if m != nil {
		return m.Origen
	}
	return ""
}

type PermisoRequest struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Pasajeros            int32    `protobuf:"varint,2,opt,name=pasajeros,proto3" json:"pasajeros,omitempty"`
	Combustible          int32    `protobuf:"varint,3,opt,name=combustible,proto3" json:"combustible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermisoRequest) Reset()         { *m = PermisoRequest{} }
func (m *PermisoRequest) String() string { return proto.CompactTextString(m) }
func (*PermisoRequest) ProtoMessage()    {}
func (*PermisoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{2}
}

func (m *PermisoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermisoRequest.Unmarshal(m, b)
}
func (m *PermisoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermisoRequest.Marshal(b, m, deterministic)
}
func (m *PermisoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermisoRequest.Merge(m, src)
}
func (m *PermisoRequest) XXX_Size() int {
	return xxx_messageInfo_PermisoRequest.Size(m)
}
func (m *PermisoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PermisoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PermisoRequest proto.InternalMessageInfo

func (m *PermisoRequest) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *PermisoRequest) GetPasajeros() int32 {
	if m != nil {
		return m.Pasajeros
	}
	return 0
}

func (m *PermisoRequest) GetCombustible() int32 {
	if m != nil {
		return m.Combustible
	}
	return 0
}

type PermisoResponse struct {
	Permiso              bool     `protobuf:"varint,1,opt,name=permiso,proto3" json:"permiso,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermisoResponse) Reset()         { *m = PermisoResponse{} }
func (m *PermisoResponse) String() string { return proto.CompactTextString(m) }
func (*PermisoResponse) ProtoMessage()    {}
func (*PermisoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{3}
}

func (m *PermisoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermisoResponse.Unmarshal(m, b)
}
func (m *PermisoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermisoResponse.Marshal(b, m, deterministic)
}
func (m *PermisoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermisoResponse.Merge(m, src)
}
func (m *PermisoResponse) XXX_Size() int {
	return xxx_messageInfo_PermisoResponse.Size(m)
}
func (m *PermisoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PermisoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PermisoResponse proto.InternalMessageInfo

func (m *PermisoResponse) GetPermiso() bool {
	if m != nil {
		return m.Permiso
	}
	return false
}

type InstruccionesRequest struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstruccionesRequest) Reset()         { *m = InstruccionesRequest{} }
func (m *InstruccionesRequest) String() string { return proto.CompactTextString(m) }
func (*InstruccionesRequest) ProtoMessage()    {}
func (*InstruccionesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{4}
}

func (m *InstruccionesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstruccionesRequest.Unmarshal(m, b)
}
func (m *InstruccionesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstruccionesRequest.Marshal(b, m, deterministic)
}
func (m *InstruccionesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstruccionesRequest.Merge(m, src)
}
func (m *InstruccionesRequest) XXX_Size() int {
	return xxx_messageInfo_InstruccionesRequest.Size(m)
}
func (m *InstruccionesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstruccionesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstruccionesRequest proto.InternalMessageInfo

func (m *InstruccionesRequest) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

type InstruccionesResponse struct {
	PistasOcupadas       bool     `protobuf:"varint,1,opt,name=pistasOcupadas,proto3" json:"pistasOcupadas,omitempty"`
	AvionPrevio          string   `protobuf:"bytes,2,opt,name=avionPrevio,proto3" json:"avionPrevio,omitempty"`
	Pista                int32    `protobuf:"varint,3,opt,name=pista,proto3" json:"pista,omitempty"`
	Altura               int32    `protobuf:"varint,4,opt,name=altura,proto3" json:"altura,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstruccionesResponse) Reset()         { *m = InstruccionesResponse{} }
func (m *InstruccionesResponse) String() string { return proto.CompactTextString(m) }
func (*InstruccionesResponse) ProtoMessage()    {}
func (*InstruccionesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{5}
}

func (m *InstruccionesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstruccionesResponse.Unmarshal(m, b)
}
func (m *InstruccionesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstruccionesResponse.Marshal(b, m, deterministic)
}
func (m *InstruccionesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstruccionesResponse.Merge(m, src)
}
func (m *InstruccionesResponse) XXX_Size() int {
	return xxx_messageInfo_InstruccionesResponse.Size(m)
}
func (m *InstruccionesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstruccionesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstruccionesResponse proto.InternalMessageInfo

func (m *InstruccionesResponse) GetPistasOcupadas() bool {
	if m != nil {
		return m.PistasOcupadas
	}
	return false
}

func (m *InstruccionesResponse) GetAvionPrevio() string {
	if m != nil {
		return m.AvionPrevio
	}
	return ""
}

func (m *InstruccionesResponse) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *InstruccionesResponse) GetAltura() int32 {
	if m != nil {
		return m.Altura
	}
	return 0
}

type ColaRequest struct {
	Pista                int32    `protobuf:"varint,1,opt,name=pista,proto3" json:"pista,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColaRequest) Reset()         { *m = ColaRequest{} }
func (m *ColaRequest) String() string { return proto.CompactTextString(m) }
func (*ColaRequest) ProtoMessage()    {}
func (*ColaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{6}
}

func (m *ColaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColaRequest.Unmarshal(m, b)
}
func (m *ColaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColaRequest.Marshal(b, m, deterministic)
}
func (m *ColaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColaRequest.Merge(m, src)
}
func (m *ColaRequest) XXX_Size() int {
	return xxx_messageInfo_ColaRequest.Size(m)
}
func (m *ColaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ColaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ColaRequest proto.InternalMessageInfo

func (m *ColaRequest) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

type ColaResponse struct {
	CabezaCola           string   `protobuf:"bytes,1,opt,name=cabezaCola,proto3" json:"cabezaCola,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColaResponse) Reset()         { *m = ColaResponse{} }
func (m *ColaResponse) String() string { return proto.CompactTextString(m) }
func (*ColaResponse) ProtoMessage()    {}
func (*ColaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{7}
}

func (m *ColaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColaResponse.Unmarshal(m, b)
}
func (m *ColaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColaResponse.Marshal(b, m, deterministic)
}
func (m *ColaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColaResponse.Merge(m, src)
}
func (m *ColaResponse) XXX_Size() int {
	return xxx_messageInfo_ColaResponse.Size(m)
}
func (m *ColaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ColaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ColaResponse proto.InternalMessageInfo

func (m *ColaResponse) GetCabezaCola() string {
	if m != nil {
		return m.CabezaCola
	}
	return ""
}

type DespegueRequest struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Pista                int32    `protobuf:"varint,2,opt,name=pista,proto3" json:"pista,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DespegueRequest) Reset()         { *m = DespegueRequest{} }
func (m *DespegueRequest) String() string { return proto.CompactTextString(m) }
func (*DespegueRequest) ProtoMessage()    {}
func (*DespegueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{8}
}

func (m *DespegueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DespegueRequest.Unmarshal(m, b)
}
func (m *DespegueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DespegueRequest.Marshal(b, m, deterministic)
}
func (m *DespegueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DespegueRequest.Merge(m, src)
}
func (m *DespegueRequest) XXX_Size() int {
	return xxx_messageInfo_DespegueRequest.Size(m)
}
func (m *DespegueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DespegueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DespegueRequest proto.InternalMessageInfo

func (m *DespegueRequest) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *DespegueRequest) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

type DespegueResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DespegueResponse) Reset()         { *m = DespegueResponse{} }
func (m *DespegueResponse) String() string { return proto.CompactTextString(m) }
func (*DespegueResponse) ProtoMessage()    {}
func (*DespegueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{9}
}

func (m *DespegueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DespegueResponse.Unmarshal(m, b)
}
func (m *DespegueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DespegueResponse.Marshal(b, m, deterministic)
}
func (m *DespegueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DespegueResponse.Merge(m, src)
}
func (m *DespegueResponse) XXX_Size() int {
	return xxx_messageInfo_DespegueResponse.Size(m)
}
func (m *DespegueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DespegueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DespegueResponse proto.InternalMessageInfo

// Aterrizaje
type AterrizajeRequest struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Linea                string   `protobuf:"bytes,2,opt,name=linea,proto3" json:"linea,omitempty"`
	Origen               string   `protobuf:"bytes,3,opt,name=origen,proto3" json:"origen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AterrizajeRequest) Reset()         { *m = AterrizajeRequest{} }
func (m *AterrizajeRequest) String() string { return proto.CompactTextString(m) }
func (*AterrizajeRequest) ProtoMessage()    {}
func (*AterrizajeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{10}
}

func (m *AterrizajeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AterrizajeRequest.Unmarshal(m, b)
}
func (m *AterrizajeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AterrizajeRequest.Marshal(b, m, deterministic)
}
func (m *AterrizajeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AterrizajeRequest.Merge(m, src)
}
func (m *AterrizajeRequest) XXX_Size() int {
	return xxx_messageInfo_AterrizajeRequest.Size(m)
}
func (m *AterrizajeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AterrizajeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AterrizajeRequest proto.InternalMessageInfo

func (m *AterrizajeRequest) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *AterrizajeRequest) GetLinea() string {
	if m != nil {
		return m.Linea
	}
	return ""
}

func (m *AterrizajeRequest) GetOrigen() string {
	if m != nil {
		return m.Origen
	}
	return ""
}

type At_InstruccionesResponse struct {
	PistasOcupadas       bool     `protobuf:"varint,1,opt,name=pistasOcupadas,proto3" json:"pistasOcupadas,omitempty"`
	AvionPrevio          string   `protobuf:"bytes,2,opt,name=avionPrevio,proto3" json:"avionPrevio,omitempty"`
	Pista                int32    `protobuf:"varint,3,opt,name=pista,proto3" json:"pista,omitempty"`
	Altura               int32    `protobuf:"varint,4,opt,name=altura,proto3" json:"altura,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *At_InstruccionesResponse) Reset()         { *m = At_InstruccionesResponse{} }
func (m *At_InstruccionesResponse) String() string { return proto.CompactTextString(m) }
func (*At_InstruccionesResponse) ProtoMessage()    {}
func (*At_InstruccionesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{11}
}

func (m *At_InstruccionesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_At_InstruccionesResponse.Unmarshal(m, b)
}
func (m *At_InstruccionesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_At_InstruccionesResponse.Marshal(b, m, deterministic)
}
func (m *At_InstruccionesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_At_InstruccionesResponse.Merge(m, src)
}
func (m *At_InstruccionesResponse) XXX_Size() int {
	return xxx_messageInfo_At_InstruccionesResponse.Size(m)
}
func (m *At_InstruccionesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_At_InstruccionesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_At_InstruccionesResponse proto.InternalMessageInfo

func (m *At_InstruccionesResponse) GetPistasOcupadas() bool {
	if m != nil {
		return m.PistasOcupadas
	}
	return false
}

func (m *At_InstruccionesResponse) GetAvionPrevio() string {
	if m != nil {
		return m.AvionPrevio
	}
	return ""
}

func (m *At_InstruccionesResponse) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

func (m *At_InstruccionesResponse) GetAltura() int32 {
	if m != nil {
		return m.Altura
	}
	return 0
}

type At_ColaRequest struct {
	Pista                int32    `protobuf:"varint,1,opt,name=pista,proto3" json:"pista,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *At_ColaRequest) Reset()         { *m = At_ColaRequest{} }
func (m *At_ColaRequest) String() string { return proto.CompactTextString(m) }
func (*At_ColaRequest) ProtoMessage()    {}
func (*At_ColaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{12}
}

func (m *At_ColaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_At_ColaRequest.Unmarshal(m, b)
}
func (m *At_ColaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_At_ColaRequest.Marshal(b, m, deterministic)
}
func (m *At_ColaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_At_ColaRequest.Merge(m, src)
}
func (m *At_ColaRequest) XXX_Size() int {
	return xxx_messageInfo_At_ColaRequest.Size(m)
}
func (m *At_ColaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_At_ColaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_At_ColaRequest proto.InternalMessageInfo

func (m *At_ColaRequest) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

type At_ColaResponse struct {
	CabezaCola           string   `protobuf:"bytes,1,opt,name=cabezaCola,proto3" json:"cabezaCola,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *At_ColaResponse) Reset()         { *m = At_ColaResponse{} }
func (m *At_ColaResponse) String() string { return proto.CompactTextString(m) }
func (*At_ColaResponse) ProtoMessage()    {}
func (*At_ColaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{13}
}

func (m *At_ColaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_At_ColaResponse.Unmarshal(m, b)
}
func (m *At_ColaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_At_ColaResponse.Marshal(b, m, deterministic)
}
func (m *At_ColaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_At_ColaResponse.Merge(m, src)
}
func (m *At_ColaResponse) XXX_Size() int {
	return xxx_messageInfo_At_ColaResponse.Size(m)
}
func (m *At_ColaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_At_ColaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_At_ColaResponse proto.InternalMessageInfo

func (m *At_ColaResponse) GetCabezaCola() string {
	if m != nil {
		return m.CabezaCola
	}
	return ""
}

type AterrizarRequest struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Pista                int32    `protobuf:"varint,2,opt,name=pista,proto3" json:"pista,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AterrizarRequest) Reset()         { *m = AterrizarRequest{} }
func (m *AterrizarRequest) String() string { return proto.CompactTextString(m) }
func (*AterrizarRequest) ProtoMessage()    {}
func (*AterrizarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{14}
}

func (m *AterrizarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AterrizarRequest.Unmarshal(m, b)
}
func (m *AterrizarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AterrizarRequest.Marshal(b, m, deterministic)
}
func (m *AterrizarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AterrizarRequest.Merge(m, src)
}
func (m *AterrizarRequest) XXX_Size() int {
	return xxx_messageInfo_AterrizarRequest.Size(m)
}
func (m *AterrizarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AterrizarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AterrizarRequest proto.InternalMessageInfo

func (m *AterrizarRequest) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *AterrizarRequest) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

type AterrizarResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AterrizarResponse) Reset()         { *m = AterrizarResponse{} }
func (m *AterrizarResponse) String() string { return proto.CompactTextString(m) }
func (*AterrizarResponse) ProtoMessage()    {}
func (*AterrizarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{15}
}

func (m *AterrizarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AterrizarResponse.Unmarshal(m, b)
}
func (m *AterrizarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AterrizarResponse.Marshal(b, m, deterministic)
}
func (m *AterrizarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AterrizarResponse.Merge(m, src)
}
func (m *AterrizarResponse) XXX_Size() int {
	return xxx_messageInfo_AterrizarResponse.Size(m)
}
func (m *AterrizarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AterrizarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AterrizarResponse proto.InternalMessageInfo

//Pantalla
type ConsultaPistasTorre struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsultaPistasTorre) Reset()         { *m = ConsultaPistasTorre{} }
func (m *ConsultaPistasTorre) String() string { return proto.CompactTextString(m) }
func (*ConsultaPistasTorre) ProtoMessage()    {}
func (*ConsultaPistasTorre) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{16}
}

func (m *ConsultaPistasTorre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsultaPistasTorre.Unmarshal(m, b)
}
func (m *ConsultaPistasTorre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsultaPistasTorre.Marshal(b, m, deterministic)
}
func (m *ConsultaPistasTorre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsultaPistasTorre.Merge(m, src)
}
func (m *ConsultaPistasTorre) XXX_Size() int {
	return xxx_messageInfo_ConsultaPistasTorre.Size(m)
}
func (m *ConsultaPistasTorre) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsultaPistasTorre.DiscardUnknown(m)
}

var xxx_messageInfo_ConsultaPistasTorre proto.InternalMessageInfo

type RespuestaPistasTorre struct {
	PistasAterrizaje     int32    `protobuf:"varint,1,opt,name=pistasAterrizaje,proto3" json:"pistasAterrizaje,omitempty"`
	PistasDespegue       int32    `protobuf:"varint,2,opt,name=pistasDespegue,proto3" json:"pistasDespegue,omitempty"`
	Torre                string   `protobuf:"bytes,3,opt,name=torre,proto3" json:"torre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespuestaPistasTorre) Reset()         { *m = RespuestaPistasTorre{} }
func (m *RespuestaPistasTorre) String() string { return proto.CompactTextString(m) }
func (*RespuestaPistasTorre) ProtoMessage()    {}
func (*RespuestaPistasTorre) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{17}
}

func (m *RespuestaPistasTorre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespuestaPistasTorre.Unmarshal(m, b)
}
func (m *RespuestaPistasTorre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespuestaPistasTorre.Marshal(b, m, deterministic)
}
func (m *RespuestaPistasTorre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespuestaPistasTorre.Merge(m, src)
}
func (m *RespuestaPistasTorre) XXX_Size() int {
	return xxx_messageInfo_RespuestaPistasTorre.Size(m)
}
func (m *RespuestaPistasTorre) XXX_DiscardUnknown() {
	xxx_messageInfo_RespuestaPistasTorre.DiscardUnknown(m)
}

var xxx_messageInfo_RespuestaPistasTorre proto.InternalMessageInfo

func (m *RespuestaPistasTorre) GetPistasAterrizaje() int32 {
	if m != nil {
		return m.PistasAterrizaje
	}
	return 0
}

func (m *RespuestaPistasTorre) GetPistasDespegue() int32 {
	if m != nil {
		return m.PistasDespegue
	}
	return 0
}

func (m *RespuestaPistasTorre) GetTorre() string {
	if m != nil {
		return m.Torre
	}
	return ""
}

type ConsultaPistaDespegue struct {
	Pista                int32    `protobuf:"varint,1,opt,name=pista,proto3" json:"pista,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsultaPistaDespegue) Reset()         { *m = ConsultaPistaDespegue{} }
func (m *ConsultaPistaDespegue) String() string { return proto.CompactTextString(m) }
func (*ConsultaPistaDespegue) ProtoMessage()    {}
func (*ConsultaPistaDespegue) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{18}
}

func (m *ConsultaPistaDespegue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsultaPistaDespegue.Unmarshal(m, b)
}
func (m *ConsultaPistaDespegue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsultaPistaDespegue.Marshal(b, m, deterministic)
}
func (m *ConsultaPistaDespegue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsultaPistaDespegue.Merge(m, src)
}
func (m *ConsultaPistaDespegue) XXX_Size() int {
	return xxx_messageInfo_ConsultaPistaDespegue.Size(m)
}
func (m *ConsultaPistaDespegue) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsultaPistaDespegue.DiscardUnknown(m)
}

var xxx_messageInfo_ConsultaPistaDespegue proto.InternalMessageInfo

func (m *ConsultaPistaDespegue) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

type RespuestaPistaDespegue struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Destino              string   `protobuf:"bytes,2,opt,name=destino,proto3" json:"destino,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespuestaPistaDespegue) Reset()         { *m = RespuestaPistaDespegue{} }
func (m *RespuestaPistaDespegue) String() string { return proto.CompactTextString(m) }
func (*RespuestaPistaDespegue) ProtoMessage()    {}
func (*RespuestaPistaDespegue) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{19}
}

func (m *RespuestaPistaDespegue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespuestaPistaDespegue.Unmarshal(m, b)
}
func (m *RespuestaPistaDespegue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespuestaPistaDespegue.Marshal(b, m, deterministic)
}
func (m *RespuestaPistaDespegue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespuestaPistaDespegue.Merge(m, src)
}
func (m *RespuestaPistaDespegue) XXX_Size() int {
	return xxx_messageInfo_RespuestaPistaDespegue.Size(m)
}
func (m *RespuestaPistaDespegue) XXX_DiscardUnknown() {
	xxx_messageInfo_RespuestaPistaDespegue.DiscardUnknown(m)
}

var xxx_messageInfo_RespuestaPistaDespegue proto.InternalMessageInfo

func (m *RespuestaPistaDespegue) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *RespuestaPistaDespegue) GetDestino() string {
	if m != nil {
		return m.Destino
	}
	return ""
}

type ConsultaPistaAterrizaje struct {
	Pista                int32    `protobuf:"varint,1,opt,name=pista,proto3" json:"pista,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsultaPistaAterrizaje) Reset()         { *m = ConsultaPistaAterrizaje{} }
func (m *ConsultaPistaAterrizaje) String() string { return proto.CompactTextString(m) }
func (*ConsultaPistaAterrizaje) ProtoMessage()    {}
func (*ConsultaPistaAterrizaje) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{20}
}

func (m *ConsultaPistaAterrizaje) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsultaPistaAterrizaje.Unmarshal(m, b)
}
func (m *ConsultaPistaAterrizaje) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsultaPistaAterrizaje.Marshal(b, m, deterministic)
}
func (m *ConsultaPistaAterrizaje) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsultaPistaAterrizaje.Merge(m, src)
}
func (m *ConsultaPistaAterrizaje) XXX_Size() int {
	return xxx_messageInfo_ConsultaPistaAterrizaje.Size(m)
}
func (m *ConsultaPistaAterrizaje) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsultaPistaAterrizaje.DiscardUnknown(m)
}

var xxx_messageInfo_ConsultaPistaAterrizaje proto.InternalMessageInfo

func (m *ConsultaPistaAterrizaje) GetPista() int32 {
	if m != nil {
		return m.Pista
	}
	return 0
}

type RespuestaPistaAterrizaje struct {
	Vuelo                string   `protobuf:"bytes,1,opt,name=vuelo,proto3" json:"vuelo,omitempty"`
	Origen               string   `protobuf:"bytes,2,opt,name=origen,proto3" json:"origen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespuestaPistaAterrizaje) Reset()         { *m = RespuestaPistaAterrizaje{} }
func (m *RespuestaPistaAterrizaje) String() string { return proto.CompactTextString(m) }
func (*RespuestaPistaAterrizaje) ProtoMessage()    {}
func (*RespuestaPistaAterrizaje) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2187aa7241f0ecf, []int{21}
}

func (m *RespuestaPistaAterrizaje) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespuestaPistaAterrizaje.Unmarshal(m, b)
}
func (m *RespuestaPistaAterrizaje) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespuestaPistaAterrizaje.Marshal(b, m, deterministic)
}
func (m *RespuestaPistaAterrizaje) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespuestaPistaAterrizaje.Merge(m, src)
}
func (m *RespuestaPistaAterrizaje) XXX_Size() int {
	return xxx_messageInfo_RespuestaPistaAterrizaje.Size(m)
}
func (m *RespuestaPistaAterrizaje) XXX_DiscardUnknown() {
	xxx_messageInfo_RespuestaPistaAterrizaje.DiscardUnknown(m)
}

var xxx_messageInfo_RespuestaPistaAterrizaje proto.InternalMessageInfo

func (m *RespuestaPistaAterrizaje) GetVuelo() string {
	if m != nil {
		return m.Vuelo
	}
	return ""
}

func (m *RespuestaPistaAterrizaje) GetOrigen() string {
	if m != nil {
		return m.Origen
	}
	return ""
}

func init() {
	proto.RegisterType((*NuevoAvionRequest)(nil), "NuevoAvionRequest")
	proto.RegisterType((*NuevoAvionResponse)(nil), "NuevoAvionResponse")
	proto.RegisterType((*PermisoRequest)(nil), "PermisoRequest")
	proto.RegisterType((*PermisoResponse)(nil), "PermisoResponse")
	proto.RegisterType((*InstruccionesRequest)(nil), "InstruccionesRequest")
	proto.RegisterType((*InstruccionesResponse)(nil), "InstruccionesResponse")
	proto.RegisterType((*ColaRequest)(nil), "ColaRequest")
	proto.RegisterType((*ColaResponse)(nil), "ColaResponse")
	proto.RegisterType((*DespegueRequest)(nil), "DespegueRequest")
	proto.RegisterType((*DespegueResponse)(nil), "DespegueResponse")
	proto.RegisterType((*AterrizajeRequest)(nil), "AterrizajeRequest")
	proto.RegisterType((*At_InstruccionesResponse)(nil), "At_InstruccionesResponse")
	proto.RegisterType((*At_ColaRequest)(nil), "At_ColaRequest")
	proto.RegisterType((*At_ColaResponse)(nil), "At_ColaResponse")
	proto.RegisterType((*AterrizarRequest)(nil), "AterrizarRequest")
	proto.RegisterType((*AterrizarResponse)(nil), "AterrizarResponse")
	proto.RegisterType((*ConsultaPistasTorre)(nil), "ConsultaPistasTorre")
	proto.RegisterType((*RespuestaPistasTorre)(nil), "RespuestaPistasTorre")
	proto.RegisterType((*ConsultaPistaDespegue)(nil), "ConsultaPistaDespegue")
	proto.RegisterType((*RespuestaPistaDespegue)(nil), "RespuestaPistaDespegue")
	proto.RegisterType((*ConsultaPistaAterrizaje)(nil), "ConsultaPistaAterrizaje")
	proto.RegisterType((*RespuestaPistaAterrizaje)(nil), "RespuestaPistaAterrizaje")
}

func init() { proto.RegisterFile("protocoloAtt.proto", fileDescriptor_a2187aa7241f0ecf) }

var fileDescriptor_a2187aa7241f0ecf = []byte{
	// 762 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0xe3, 0x36,
	0x10, 0x95, 0x93, 0xf5, 0xee, 0x7a, 0xd6, 0x6b, 0xcb, 0x8c, 0xed, 0x28, 0x42, 0x50, 0x04, 0x2c,
	0x10, 0x04, 0xfd, 0x60, 0xd1, 0xe6, 0xd0, 0x43, 0x9b, 0x02, 0x42, 0x52, 0xa0, 0x69, 0x81, 0xd6,
	0x70, 0x8b, 0xf6, 0x18, 0xd0, 0x32, 0x13, 0x30, 0x50, 0x44, 0x95, 0xa4, 0x7c, 0xc8, 0xa9, 0xff,
	0xa0, 0x40, 0xff, 0x4b, 0xff, 0x5f, 0x21, 0x8a, 0xb2, 0x29, 0x59, 0x4e, 0x8a, 0x9c, 0xf6, 0x96,
	0x19, 0x91, 0x7c, 0x6f, 0xe6, 0xcd, 0xbc, 0x18, 0x50, 0x26, 0x85, 0x16, 0xb1, 0x48, 0x44, 0xa4,
	0x35, 0x31, 0x01, 0xfe, 0xbb, 0x03, 0xa3, 0x9f, 0x73, 0xb6, 0x12, 0xd1, 0x8a, 0x8b, 0x74, 0xce,
	0xfe, 0xcc, 0x99, 0xd2, 0x68, 0x0c, 0xdd, 0x55, 0xce, 0x12, 0x11, 0x74, 0x4e, 0x3a, 0x67, 0xbd,
	0x79, 0x19, 0x14, 0xd9, 0x84, 0xa7, 0x8c, 0x06, 0x7b, 0x65, 0xd6, 0x04, 0x28, 0x80, 0x37, 0x4b,
	0xa6, 0x34, 0x4f, 0x45, 0xb0, 0x6f, 0xf2, 0x55, 0x88, 0x10, 0xbc, 0xca, 0x98, 0x12, 0xc1, 0xab,
	0x93, 0xce, 0x59, 0x77, 0x6e, 0xfe, 0x46, 0x27, 0xf0, 0x2e, 0x16, 0x0f, 0x8b, 0x5c, 0x69, 0xbe,
	0x48, 0x58, 0xd0, 0x35, 0x9f, 0xdc, 0x14, 0xfe, 0x11, 0x90, 0x4b, 0x48, 0x65, 0x22, 0x55, 0x0c,
	0x1d, 0x43, 0x6f, 0xc9, 0x25, 0x8b, 0x63, 0x2e, 0x52, 0xcb, 0x6a, 0x93, 0x40, 0x53, 0x78, 0x2d,
	0x24, 0xbf, 0x63, 0xa9, 0xa5, 0x66, 0x23, 0x7c, 0x0b, 0x83, 0x19, 0x93, 0x0f, 0x5c, 0x89, 0xa7,
	0x2b, 0x3b, 0x86, 0x5e, 0x46, 0x15, 0xbd, 0x67, 0x52, 0x28, 0xf3, 0x44, 0x77, 0xbe, 0x49, 0x34,
	0x39, 0xef, 0x6f, 0x73, 0xfe, 0x14, 0x86, 0x6b, 0x1c, 0x4b, 0x38, 0x80, 0x37, 0x59, 0x99, 0x32,
	0x50, 0x6f, 0xe7, 0x55, 0x88, 0x3f, 0x83, 0xf1, 0x75, 0xaa, 0xb4, 0xcc, 0x0d, 0x77, 0xa6, 0x9e,
	0xa4, 0x56, 0x08, 0x34, 0x69, 0x1c, 0xb7, 0x08, 0xa7, 0x30, 0xc8, 0xb8, 0xd2, 0x54, 0xfd, 0x12,
	0xe7, 0x19, 0x5d, 0x52, 0x65, 0x81, 0x1a, 0xd9, 0x82, 0x3e, 0x2d, 0x7a, 0x39, 0x93, 0x6c, 0xc5,
	0x85, 0xed, 0x90, 0x9b, 0x2a, 0x90, 0xcd, 0x1d, 0x5b, 0x5a, 0x19, 0x14, 0x4d, 0xa5, 0x89, 0xce,
	0x25, 0xb5, 0x02, 0xda, 0x08, 0x7f, 0x0c, 0xef, 0x2e, 0x45, 0x42, 0x1d, 0xda, 0xe5, 0xe5, 0x8e,
	0x73, 0x19, 0x13, 0xe8, 0x97, 0x87, 0x2c, 0xd9, 0x8f, 0x00, 0x62, 0xba, 0x60, 0x8f, 0xb4, 0xc8,
	0xda, 0x0a, 0x9d, 0x0c, 0xbe, 0x80, 0xe1, 0x15, 0x53, 0x19, 0xbb, 0xcb, 0xd9, 0xb3, 0x43, 0x58,
	0xc2, 0xed, 0xb9, 0x70, 0x08, 0xfc, 0xcd, 0xf5, 0x12, 0x12, 0xff, 0x01, 0xa3, 0x48, 0x33, 0x29,
	0xf9, 0x23, 0xbd, 0x67, 0x2f, 0x99, 0xec, 0xcd, 0x54, 0xed, 0xd7, 0xa6, 0xea, 0x9f, 0x0e, 0x04,
	0x91, 0xbe, 0xf9, 0xb0, 0x54, 0x39, 0x85, 0x41, 0xa4, 0x6f, 0x9e, 0x17, 0xe6, 0x4b, 0x18, 0xae,
	0xcf, 0xfd, 0x4f, 0x6d, 0xbe, 0x03, 0xbf, 0x6a, 0xa4, 0x7c, 0x89, 0x38, 0x07, 0x1b, 0x21, 0xe4,
	0x5a, 0x9d, 0x09, 0x1c, 0x5c, 0x8a, 0x54, 0xe5, 0x89, 0xa6, 0x33, 0xd3, 0x99, 0xdf, 0x84, 0x94,
	0x0c, 0xff, 0xd5, 0x81, 0x71, 0x71, 0xa6, 0x00, 0x71, 0x3f, 0xa0, 0x4f, 0xc0, 0x2f, 0x3b, 0xb8,
	0xd1, 0xd4, 0x16, 0xb6, 0x95, 0xdf, 0x68, 0x50, 0xcd, 0x84, 0xe5, 0xd3, 0xc8, 0x16, 0x74, 0x75,
	0xf1, 0xb8, 0xd5, 0xb7, 0x0c, 0xf0, 0xe7, 0x30, 0xa9, 0x31, 0x73, 0x8f, 0xb7, 0x34, 0xf4, 0x07,
	0x98, 0xd6, 0x09, 0xbb, 0xe7, 0x5b, 0x7a, 0xe4, 0xf8, 0xe5, 0x5e, 0xcd, 0x2f, 0xf1, 0x17, 0x70,
	0x58, 0x03, 0x76, 0x2a, 0xda, 0x05, 0x1d, 0xd4, 0xa1, 0xeb, 0x37, 0x5a, 0xc0, 0x77, 0x18, 0xe5,
	0x57, 0xff, 0x76, 0xe1, 0xed, 0xaf, 0x4c, 0xae, 0x78, 0xcc, 0x05, 0xba, 0x00, 0xbf, 0xe2, 0x21,
	0xaf, 0x2a, 0x2f, 0x27, 0x5b, 0xff, 0x25, 0xc2, 0x03, 0xb2, 0x6d, 0xd4, 0xd8, 0x43, 0xe7, 0xd0,
	0x9f, 0xb1, 0x25, 0x97, 0xd6, 0x11, 0xd1, 0x90, 0xd4, 0x3d, 0x38, 0xf4, 0x49, 0xc3, 0x2c, 0xb1,
	0x87, 0xbe, 0x07, 0x64, 0x2e, 0xd5, 0x96, 0x0a, 0x4d, 0x48, 0x9b, 0x53, 0x86, 0x53, 0xd2, 0xba,
	0x7b, 0xd8, 0x43, 0x04, 0xde, 0xff, 0xce, 0x24, 0xbf, 0xe5, 0x31, 0x95, 0xc5, 0xec, 0xa2, 0x3e,
	0x71, 0x56, 0x22, 0x7c, 0x4f, 0xdc, 0xc1, 0xc7, 0x1e, 0xfa, 0x1a, 0x06, 0xd1, 0x8a, 0x2b, 0x53,
	0x67, 0x29, 0x9a, 0x4f, 0x1a, 0x3e, 0x14, 0x8e, 0xc8, 0x96, 0xb5, 0x78, 0xe8, 0x5b, 0xe8, 0x45,
	0x5a, 0x33, 0x33, 0xd3, 0x08, 0x91, 0x2d, 0xa3, 0x09, 0x8f, 0xc8, 0x2e, 0x8b, 0x30, 0xb0, 0x7e,
	0x8d, 0xe6, 0x4d, 0xa4, 0xd1, 0x90, 0xd4, 0xf7, 0x37, 0xf4, 0x49, 0x63, 0x51, 0xb1, 0x87, 0xbe,
	0x01, 0xbf, 0xe4, 0xeb, 0x28, 0x3d, 0x22, 0xcd, 0xed, 0x0c, 0x11, 0xd9, 0x5e, 0x38, 0x0f, 0x5d,
	0x40, 0x7f, 0x46, 0x53, 0x4d, 0x93, 0x84, 0x5e, 0xa7, 0x5c, 0xa3, 0x31, 0x69, 0xd9, 0xc0, 0x70,
	0x42, 0xda, 0xf6, 0xcf, 0x48, 0xe4, 0x57, 0xd7, 0xd7, 0xdd, 0x9a, 0x92, 0xd6, 0x55, 0x09, 0x0f,
	0x49, 0xfb, 0x4e, 0x60, 0x0f, 0xfd, 0x04, 0xa8, 0x7a, 0xc6, 0x29, 0x22, 0x20, 0x3b, 0x46, 0x3f,
	0x3c, 0x22, 0xbb, 0x66, 0x1c, 0x7b, 0x8b, 0xd7, 0xe6, 0x57, 0xcc, 0xf9, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x4f, 0xd4, 0x96, 0xd5, 0xdb, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServicioClient is the client API for Servicio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServicioClient interface {
	ConsultarDestino(ctx context.Context, in *NuevoAvionRequest, opts ...grpc.CallOption) (*NuevoAvionResponse, error)
	PedirPermiso(ctx context.Context, in *PermisoRequest, opts ...grpc.CallOption) (*PermisoResponse, error)
	PedirInstrucciones(ctx context.Context, in *InstruccionesRequest, opts ...grpc.CallOption) (*InstruccionesResponse, error)
	VerificarCola(ctx context.Context, in *ColaRequest, opts ...grpc.CallOption) (*ColaResponse, error)
	AvisarDespegue(ctx context.Context, in *DespegueRequest, opts ...grpc.CallOption) (*DespegueResponse, error)
	//
	Atterizar(ctx context.Context, in *AterrizajeRequest, opts ...grpc.CallOption) (*At_InstruccionesResponse, error)
	VerificarCola_At(ctx context.Context, in *At_ColaRequest, opts ...grpc.CallOption) (*At_ColaResponse, error)
	AvisarAterrizaje(ctx context.Context, in *AterrizarRequest, opts ...grpc.CallOption) (*AterrizarResponse, error)
	//
	PantallaInit(ctx context.Context, in *ConsultaPistasTorre, opts ...grpc.CallOption) (*RespuestaPistasTorre, error)
	PantallaDespegue(ctx context.Context, in *ConsultaPistaDespegue, opts ...grpc.CallOption) (*RespuestaPistaDespegue, error)
	PantallaAterrizaje(ctx context.Context, in *ConsultaPistaAterrizaje, opts ...grpc.CallOption) (*RespuestaPistaAterrizaje, error)
}

type servicioClient struct {
	cc *grpc.ClientConn
}

func NewServicioClient(cc *grpc.ClientConn) ServicioClient {
	return &servicioClient{cc}
}

func (c *servicioClient) ConsultarDestino(ctx context.Context, in *NuevoAvionRequest, opts ...grpc.CallOption) (*NuevoAvionResponse, error) {
	out := new(NuevoAvionResponse)
	err := c.cc.Invoke(ctx, "/Servicio/ConsultarDestino", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) PedirPermiso(ctx context.Context, in *PermisoRequest, opts ...grpc.CallOption) (*PermisoResponse, error) {
	out := new(PermisoResponse)
	err := c.cc.Invoke(ctx, "/Servicio/PedirPermiso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) PedirInstrucciones(ctx context.Context, in *InstruccionesRequest, opts ...grpc.CallOption) (*InstruccionesResponse, error) {
	out := new(InstruccionesResponse)
	err := c.cc.Invoke(ctx, "/Servicio/PedirInstrucciones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) VerificarCola(ctx context.Context, in *ColaRequest, opts ...grpc.CallOption) (*ColaResponse, error) {
	out := new(ColaResponse)
	err := c.cc.Invoke(ctx, "/Servicio/VerificarCola", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) AvisarDespegue(ctx context.Context, in *DespegueRequest, opts ...grpc.CallOption) (*DespegueResponse, error) {
	out := new(DespegueResponse)
	err := c.cc.Invoke(ctx, "/Servicio/AvisarDespegue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) Atterizar(ctx context.Context, in *AterrizajeRequest, opts ...grpc.CallOption) (*At_InstruccionesResponse, error) {
	out := new(At_InstruccionesResponse)
	err := c.cc.Invoke(ctx, "/Servicio/Atterizar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) VerificarCola_At(ctx context.Context, in *At_ColaRequest, opts ...grpc.CallOption) (*At_ColaResponse, error) {
	out := new(At_ColaResponse)
	err := c.cc.Invoke(ctx, "/Servicio/VerificarCola_At", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) AvisarAterrizaje(ctx context.Context, in *AterrizarRequest, opts ...grpc.CallOption) (*AterrizarResponse, error) {
	out := new(AterrizarResponse)
	err := c.cc.Invoke(ctx, "/Servicio/AvisarAterrizaje", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) PantallaInit(ctx context.Context, in *ConsultaPistasTorre, opts ...grpc.CallOption) (*RespuestaPistasTorre, error) {
	out := new(RespuestaPistasTorre)
	err := c.cc.Invoke(ctx, "/Servicio/PantallaInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) PantallaDespegue(ctx context.Context, in *ConsultaPistaDespegue, opts ...grpc.CallOption) (*RespuestaPistaDespegue, error) {
	out := new(RespuestaPistaDespegue)
	err := c.cc.Invoke(ctx, "/Servicio/PantallaDespegue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioClient) PantallaAterrizaje(ctx context.Context, in *ConsultaPistaAterrizaje, opts ...grpc.CallOption) (*RespuestaPistaAterrizaje, error) {
	out := new(RespuestaPistaAterrizaje)
	err := c.cc.Invoke(ctx, "/Servicio/PantallaAterrizaje", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicioServer is the server API for Servicio service.
type ServicioServer interface {
	ConsultarDestino(context.Context, *NuevoAvionRequest) (*NuevoAvionResponse, error)
	PedirPermiso(context.Context, *PermisoRequest) (*PermisoResponse, error)
	PedirInstrucciones(context.Context, *InstruccionesRequest) (*InstruccionesResponse, error)
	VerificarCola(context.Context, *ColaRequest) (*ColaResponse, error)
	AvisarDespegue(context.Context, *DespegueRequest) (*DespegueResponse, error)
	//
	Atterizar(context.Context, *AterrizajeRequest) (*At_InstruccionesResponse, error)
	VerificarCola_At(context.Context, *At_ColaRequest) (*At_ColaResponse, error)
	AvisarAterrizaje(context.Context, *AterrizarRequest) (*AterrizarResponse, error)
	//
	PantallaInit(context.Context, *ConsultaPistasTorre) (*RespuestaPistasTorre, error)
	PantallaDespegue(context.Context, *ConsultaPistaDespegue) (*RespuestaPistaDespegue, error)
	PantallaAterrizaje(context.Context, *ConsultaPistaAterrizaje) (*RespuestaPistaAterrizaje, error)
}

func RegisterServicioServer(s *grpc.Server, srv ServicioServer) {
	s.RegisterService(&_Servicio_serviceDesc, srv)
}

func _Servicio_ConsultarDestino_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NuevoAvionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).ConsultarDestino(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/ConsultarDestino",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).ConsultarDestino(ctx, req.(*NuevoAvionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_PedirPermiso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PermisoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).PedirPermiso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/PedirPermiso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).PedirPermiso(ctx, req.(*PermisoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_PedirInstrucciones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstruccionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).PedirInstrucciones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/PedirInstrucciones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).PedirInstrucciones(ctx, req.(*InstruccionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_VerificarCola_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).VerificarCola(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/VerificarCola",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).VerificarCola(ctx, req.(*ColaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_AvisarDespegue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DespegueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).AvisarDespegue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/AvisarDespegue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).AvisarDespegue(ctx, req.(*DespegueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_Atterizar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AterrizajeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).Atterizar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/Atterizar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).Atterizar(ctx, req.(*AterrizajeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_VerificarCola_At_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(At_ColaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).VerificarCola_At(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/VerificarCola_At",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).VerificarCola_At(ctx, req.(*At_ColaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_AvisarAterrizaje_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AterrizarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).AvisarAterrizaje(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/AvisarAterrizaje",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).AvisarAterrizaje(ctx, req.(*AterrizarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_PantallaInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultaPistasTorre)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).PantallaInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/PantallaInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).PantallaInit(ctx, req.(*ConsultaPistasTorre))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_PantallaDespegue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultaPistaDespegue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).PantallaDespegue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/PantallaDespegue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).PantallaDespegue(ctx, req.(*ConsultaPistaDespegue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Servicio_PantallaAterrizaje_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultaPistaAterrizaje)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioServer).PantallaAterrizaje(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Servicio/PantallaAterrizaje",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioServer).PantallaAterrizaje(ctx, req.(*ConsultaPistaAterrizaje))
	}
	return interceptor(ctx, in, info, handler)
}

var _Servicio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Servicio",
	HandlerType: (*ServicioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultarDestino",
			Handler:    _Servicio_ConsultarDestino_Handler,
		},
		{
			MethodName: "PedirPermiso",
			Handler:    _Servicio_PedirPermiso_Handler,
		},
		{
			MethodName: "PedirInstrucciones",
			Handler:    _Servicio_PedirInstrucciones_Handler,
		},
		{
			MethodName: "VerificarCola",
			Handler:    _Servicio_VerificarCola_Handler,
		},
		{
			MethodName: "AvisarDespegue",
			Handler:    _Servicio_AvisarDespegue_Handler,
		},
		{
			MethodName: "Atterizar",
			Handler:    _Servicio_Atterizar_Handler,
		},
		{
			MethodName: "VerificarCola_At",
			Handler:    _Servicio_VerificarCola_At_Handler,
		},
		{
			MethodName: "AvisarAterrizaje",
			Handler:    _Servicio_AvisarAterrizaje_Handler,
		},
		{
			MethodName: "PantallaInit",
			Handler:    _Servicio_PantallaInit_Handler,
		},
		{
			MethodName: "PantallaDespegue",
			Handler:    _Servicio_PantallaDespegue_Handler,
		},
		{
			MethodName: "PantallaAterrizaje",
			Handler:    _Servicio_PantallaAterrizaje_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocoloAtt.proto",
}
